#!/bin/bash

if [[ "$1" == "travis-ci" ]]; then
  echo 'mode: atomic' > profile.cov && go list ./... | grep -v /vendor/ | xargs -n1 -I{} sh -c 'go test -tags server -covermode=atomic -coverprofile=profile.tmp {} && tail -n +2 profile.tmp >> profile.cov' && rm profile.tmp
else
  go test -tags "$*" $(go list ./... | grep -v /vendor/) -cover
fi
